name: Portuguese
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  validate-yml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate mkdocs yml
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: |
          node yamlPagesValidator.js pt

  deploy:
    needs: validate-yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials, Build and Deploy
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install mkdocs-redirects
      - run: bash -c 'cd pt && git pull && mkdocs gh-deploy'

      - name: Checkout
        uses: actions/checkout@v1